# Generated by Django 4.2.5 on 2023-09-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='call_as',
            new_name='call_us',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='email_as',
            new_name='email_us',
        ),
    ]
