# Generated by Django 4.2.5 on 2023-10-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdetail',
            name='Cart',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detait', to='orders.cart'),
        ),
    ]
