# Generated by Django 4.2.5 on 2023-10-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_cartdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='orders.cart'),
        ),
    ]
