# Generated by Django 4.2.5 on 2023-09-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vidio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
